apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pacificadispatchers.dispatcher.pacifica.io
spec:
  group: dispatcher.pacifica.io
  names:
    kind: PacificaDispatcher
    listKind: PacificaDispatcherList
    plural: pacificadispatchers
    singular: pacificadispatcher
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
