---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    k8s-app: postgresql
spec:
  selector:
    k8s-app: postgresql
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
