---
kind: Secret
metadata:
  name: "dispatcher-secret"
type: Opaque
stringData:
  proto: postgresql
  host: postgresql
  user: pacifica
  pass: pacifica
  name: pacifica
  db_url: postgresql://pacifica:pacifica@postgresql:5432/pacifica
  broker_url: redis://redis:6379/0
