---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacifica-dispatcher-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacifica-dispatcher-operator
  template:
    metadata:
      labels:
        name: pacifica-dispatcher-operator
    spec:
      serviceAccountName: pacifica-dispatcher-operator
      containers:
        - name: pacifica-dispatcher-operator
          # Replace this with the built image name
          image: "REPLACE_IMAGE"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "pacifica-dispatcher-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
