---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "dispatcher-shared-pv"
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/dispatcherdata"
