---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "dispatcher-shared-pvc"
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
