---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  collections:
    - community.kubernetes
  vars:
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
  tasks:
    - name: Create Custom Resource Definition
      k8s:
        definition: |
          {{ lookup('file', '/'.join([deploy_dir, 'crds/dispatcher.pacifica.io_pacificadispatchers_crd.yaml'])) }}
    - name: Create namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
    - name: Create K8S resources
      k8s:
        definition: "{{ lookup('template', '/'.join([deploy_dir, item])) }}"
        namespace: '{{ namespace }}'
      with_items:
        - role.yaml
        - role_binding.yaml
        - service_account.yaml
        - db-pv.yaml
        - db-pvc.yaml
        - db-postgres-deployment.yaml
        - db-postgres-service.yaml
        - db-secret.yaml
        - msg-redis-deployment.yaml
        - msg-redis-service.yaml
        - shared-pv.yaml
        - shared-pvc.yaml
